apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskapp

resources:
  - namespace.yaml
  - storage-class.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml

commonLabels:
  app.kubernetes.io/part-of: taskapp
  app.kubernetes.io/managed-by: kustomize
